kind: pipeline

steps:
- name: compile
  image: microsoft/dotnet:sdk
  commands:
    - sh build.sh
- name: build-image
  image: plugins/docker
  settings:
    username:houqijun111
    password: houhouhou
    repo: houqijun111/dotnetcore-container
    dockerfile: Web/Dockerfile
